### PR TITLE
Add CapitalGo 2017 videos

### PR DESCRIPTION
**Pull request by cgt**
Also fix a JSON syntax error.

### CODE REVIEW

**Comment by dgryski** [comment]
Thanks!  I have a huge backlog​ to go through but this helps a bunch.  I'll try to get this deployed tomorrow.

**Comment by cgt** [comment]
I'd be happy to help out with the backlog. I was thinking of doing [Just for Func](https://www.youtube.com/playlist?list=PL64wiCrrxh4Jisi7OcCJIUpguV_f5jGnZ). Anything else?

**Comment by dgryski** [comment]
In addition to GopherCon SG 2017: http://www.youtube.com/playlist?list=PLq2Nv-Sh8EbZEjZdPLaQt1qh_ohZFMDj8 there's also everything on gophervids: http://www.youtube.com/playlist?list=PLiAILMXD9huEKtg1Lyx0PO6Ki1WaJSyR5 and I think I've missed a few dotGo talks even.

My spring has been very busy :/

**Comment by dgryski** [comment]
Let me see if I can figure out a way to add you to the appengine thing so you can deploy too.

**Comment by dgryski** [comment]
If you have a YouTube API key, the `ytimport` program can speed this up considerably.  Then I run it through `sort.go` so the dates are in the proper order.

**Comment by cgt** [comment]
I do have a YouTube API key, and I actually wrote my own program to automate some of this for my previous pull requests. Only noticed ytimport.go tonight and I'm looking at making some improvements (ability to get info for playlist natively from the API without having to curl|grep|sed, flag for adding a tag to all the videos from the playlist, maybe other things).

**Comment by cgt** [comment]
Added Gophercon SG 2017 vids as well as some minor changes/fixes.

Thanks for adding me as a collaborator on the repo; should I just merge the PR myself? And for later additions, should I still make PRs or should I just push my commits to master?

**Comment by dgryski** [comment]
It's fine to push to master.  I'll try to find a way to automate the appengine deploys too.

**Comment by dgryski** [comment]
I've just deployed this.

**Pull request merged**
